# Dockerfile_api
FROM python:3.8-slim

# Passer à l'utilisateur root pour installer les dépendances système
USER root

# Installer les dépendances système nécessaires pour psycopg2 et autres
RUN apt-get update && apt-get install -y \
    libpq-dev \
    python3-dev \
    build-essential \
    && apt-get clean

# Copier l'application
COPY ./app /app

# Copier le fichier requirements.txt dans le conteneur
COPY ./requirements_api.txt /app/requirements.txt

# Installer les dépendances Python
RUN pip install --no-cache-dir -r /app/requirements.txt

# Définir le répertoire de travail
WORKDIR /app

# Exposer le port de l'application
EXPOSE 8000

# Lancer l'application FastAPI
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
