# Dockerfile_airflow
FROM apache/airflow:2.8.1

# Passer à l'utilisateur root pour installer les dépendances système
USER root

# Installation des dépendances système nécessaires pour psycopg2
RUN apt-get update && apt-get install -y \
    libpq-dev \
    python3-dev \
    build-essential \
    && apt-get clean

# Installation du node-exporter
COPY ./monitoring/bin/node_exporter /bin/
COPY ./monitoring/bin/statsd_exporter /bin/
COPY ./monitoring/bin/my_entrypoint.sh /
RUN chmod 755 /bin/node_exporter /bin/statsd_exporter /my_entrypoint.sh

# Revenir à l'utilisateur airflow pour les dernières configurations
USER airflow

# Copier le fichier requirements_airflow.txt
COPY ./requirements_airflow.txt /opt/airflow/requirements.txt

# Installation des dépendances Python spécifiques à Airflow
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt

# Copier les DAGs, scripts, et SQL dans Airflow
COPY ./app /opt/airflow/app
COPY ./dags /opt/airflow/dags
COPY ./scripts /opt/airflow/scripts
COPY ./sql /opt/airflow/sql

EXPOSE 9100 9102

ENTRYPOINT ["/usr/bin/dumb-init", "--", "/my_entrypoint.sh"]
