# Dockerfile_airflow
FROM apache/airflow:2.8.1

# Passer à l'utilisateur root pour installer les dépendances système
USER root

# Installation des dépendances système nécessaires pour psycopg2
RUN apt-get update && apt-get install -y \
    libpq-dev \
    python3-dev \
    build-essential \
    && apt-get clean

# Copier le fichier requirements_airflow.txt
COPY ./requirements_airflow.txt /opt/airflow/requirements.txt

# Installation des dépendances Python spécifiques à Airflow
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt

# Copier les DAGs, scripts, et SQL dans Airflow
COPY ./dags /opt/airflow/dags
COPY ./scripts /opt/airflow/scripts
COPY ./sql /opt/airflow/sql
COPY ./model /opt/airflow/model

# Revenir à l'utilisateur airflow pour les dernières configurations
USER airflow

