# Dockerfile_api
FROM python:3.8-slim

# Passer à l'utilisateur root pour installer les dépendances système
USER root

# Installer les dépendances système nécessaires pour psycopg2 et autres
RUN apt-get update && apt-get install -y \
    libpq-dev \
    python3-dev \
    build-essential \
    && apt-get clean

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier requirements_api.txt dans le conteneur
COPY ./requirements_api.txt /app/requirements.txt

# Installer les dépendances Python
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copier le reste de l'application
COPY ./app /app
COPY ./scripts /app/scripts

# Installation du node-exporter
COPY ./monitoring/bin/node_exporter /bin/
RUN chmod 755 /bin/node_exporter

# Exposer le port de l'application et du node-exporter
EXPOSE 8000 9100

# Lancer l'application FastAPI et le node-exporter
CMD /bin/node_exporter --web.listen-address=:9100 & uvicorn app:app --host 0.0.0.0 --port 8000
