# Dockerfile_airflow
FROM apache/airflow:2.8.1

# Passer à l'utilisateur root pour installer les dépendances système
USER root

# Installation des dépendances système nécessaires pour psycopg2
RUN apt-get update && apt-get install -y \
    libpq-dev \
    python3-dev \
    build-essential \
    && apt-get clean

# Revenir à l'utilisateur airflow pour installer les paquets Python
USER airflow

# Copier le fichier requirements.txt
COPY ./requirements_airflow.txt /opt/airflow/requirements.txt

# Installation des dépendances Python spécifiques à Airflow
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt

# Copier les scripts et les DAGs Airflow
COPY ./dags    /opt/airflow/dags
COPY ./model   /opt/airflow/model
COPY ./scripts /opt/airflow/scripts
COPY ./sql     /opt/airflow/sql
COPY ./users   /opt/airflow/users
